### ISSUE TITLE
./makeoptdoc: No such file or directory

### ISSUE THREAD

**Issue by protektwar** [Hordeking/vmips#1]
Is there a solution for this error?

make[2]: Entering directory '/home/user/projects/vmips/doc'
cd . && ./makeoptdoc options.texi
/bin/bash: line 1: ./makeoptdoc: No such file or directory
make[2]: *** [Makefile:730: options.texi] Error 127

**Comment by Hordeking** [comment]
From the look of it, the makeoptdoc script doesn't even exist in there. It could be that the author removed it at some point. I'm not sure when it was a thing. If you really need to get to the bottom of this, I would recommend you reach out to the author Brian through his website http://vmips.sourceforge.net/vmips/index.shtml

I've only been taking his releases and putting them into git commits, really this is more for myself and I did this before github allowed regular users to have private repos. So in effect I'm only mirroring his releases.

If it's something you want to work on, I will probably have more time to tinker with this when I go back to days for my job in late fall -- right now I'm working 13 to 16 hour days if you include my drive time and don't have a lot of time for much besides sleeping.

**Comment by protektwar** [comment]
Thanks for the info!
